name: Semver Github Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.semrel.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.version != ''
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64, darwin/amd64
        goos: [ linux, windows, darwin ]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Install Wails
        run: go install github.com/wailsapp/wails/cmd/wails@latest
      - uses: actions/checkout@v2
      - run: |
        wails build
        mv ./build/waterfall ./build/waterfall-${{matrix.goos}}-${{matrix.goarch}}
      - uses: softprops/action-gh-release@v1
        with:
          files: build/*
#      - uses: wangyoucao577/go-release-action@v1.21
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          goos: ${{ matrix.goos }}
#          goarch: ${{ matrix.goarch }}
#          goversion: "https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz"
#          pre_command: "make ci"
#          build_command: "make build"
#          release_tag: ${{needs.release.outputs.version}}
#          overwrite: true
##          asset_name: "test-${{ needs.release.output.version }}-${{ matrix.goos }}-${{ matrix.goarch }}"
#          retry: 60
